name: ci

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Node.js 20.x
            node-version: '20.19.0'
          - name: Node.js 24.x
            node-version: '24'

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js ${{ matrix.node-version }}
        shell: bash -eo pipefail -l {0}
        run: |
          nvm install --default ${{ matrix.node-version }}
          dirname "$(nvm which ${{ matrix.node-version }})" >> "$GITHUB_PATH"

      - name: Configure npm
        run: |
          if [[ "$(npm config get package-lock)" == "true" ]]; then
            npm config set package-lock false
          else
            npm config set shrinkwrap false
          fi

      - name: Install Node.js dependencies
        run: npm i pnpm -g && pnpm install

      - name: Run tests
        run: pnpm run build && pnpm run test
